config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]


    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root to: 'pages#index'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Authorship
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  scope :all_by_tags, -> (tag_ids) do
    questions = includes(:user, :question_tags, :tags)

    if tag_ids
      questions = questions.includes(question_tags: :tag).joins(:tags).where(tags: { id: tag_ids })
    else
      questions = questions.includes(:question_tags, :tags)
    end

    questions.order(created_at: :desc)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include QuestionsAnswers

  before_action :require_authentication, except: %i[show index]
  before_action :set_question!, only: %i[show edit destroy update]
  before_action :fetch_tags, only: %i[new edit]
  before_action :authorize_question!
  after_action :verify_authorized

  def index
    @pagy, @questions = pagy Question.all_by_tags(params[:tag_ids]),
                             link_extra: "data-turbo-frame=pagination"
    @questions = @questions.decorate
  end

  def show
    load_questions_answers
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params

    if @question.save
      set_respond_to questions_path, (t ".success"),
                     query_decorate: true
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @question.update question_params
      set_respond_to questions_path, (t ".success"),
                                    query_decorate:true
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit; end

  def destroy
    @question.destroy
    set_respond_to [questions_path, status: :see_other],
                   (t ".deleted")
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find(params[:id])
  end

  def fetch_tags
    @tags = Tag.all
  end

  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_form.html.erb
<%= turbo_frame_tag @question do %>
  <%= form_with model: @question, data: {turbo: false } do |form| %>
    <%=  render "shared/errors", object: @question %>
    <div class="flex flex-col gap-4 w-full">

      <div class="flex flex-col gap-2">
        <%= form.label :title, class: 'w-96' %>
        <%= form.text_field :title, placeholder: "Title", class: 'w-96' %>
        <%= form.label :body, class: "w-96" %>
        <%= form.text_area :body, placeholder: "Body", class: "w-96" %>
      </div>


      <div class="mt-2 flex flex-col">
        <%= form.label :tags, class: 'w-96' %>
        <%= form.collection_select :tag_ids, tags, :id, :title, {}, multiple: true, class: " text-black w-96" %>
      </div>

      <div class="mt-2">
        <%= form.submit "Submit question", class: "btn-primary bg-blue-600" %>
        <%= link_to "Back", :back, class: "" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/questions/_question.html.erb
<%= turbo_frame_tag question do %>
  <div class="card mt-4">
    <section class="border-b pb-2">
      <h2 class="font-bold text-xl flex gap-2 items-center">
        <%= question.user.gravatar %>
        <%= question.user.name_or_email %>
      </h2>
    </section>

    <h4 class="font-bold text-3xl">
      <%= link_to question.title, question_path(question), data: { turbo_frame: '_top'} %>
    </h4>

    <time datetime="<%= question.formatted_created_at %>">
      <p class="text-gray-500">
        <%= question.formatted_created_at %>
      </p>
    </time>

    <div>
      <%= render question.tags %>
    </div>

    <p><%= sanitize question.body, length: 150, omission: '...(continued)'  %></p>

    <div class="flex gap-1">
      <%#= link_to "Show", question_path(question), class: "btn-primary bg-blue-500" %>

      <% if policy(question).edit? %>
        <%= link_to "Edit", edit_question_path(question), class: "btn-primary bg-gray-500" %>
      <% end %>

      <% if policy(question).destroy? %>
        <%= link_to "Delete", question_path(question), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-primary bg-red-500" %>
      <% end %>

    </div>
  </div>
<% end %>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.prepend 'questions', render(@question) %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>

app/views/questions/edit.html.erb
<div class="content w-full">
  <%= currently_at "Questions" %>
  <%= provide :page_title, "Edit question" %>

  <h1 class="text-2xl">Edit question</h1>

  <%= render 'form', tags: @tags %>
</div>

app/views/questions/index.html.erb
<%= provide :page_title, "Questions" %>
<% currently_at t("questions.index") %>

<div class="content">
  <h1 class="text-3xl">Questions</h1>
  <div class="flex justify-start items-start flex-col">
    <% if policy(:question).new? %>
      <%= link_to "New question", new_question_path, class: "btn-primary bg-gray-500", data: { turbo_frame: dom_id(Question.new) } %>

      <div class="my-2">
        <%= turbo_frame_tag Question.new %>
      </div>

    <% end %>
  </div>

  <%= turbo_frame_tag 'pagination_pagy' do %>
    <div>
      <%== pagy_nav @pagy %>
    </div>

    <%= turbo_frame_tag 'questions' do  %>
      <%= render @questions %>
    <% end %>
  <% end %>

</div>

app/views/questions/new.html.erb
<div class="content">
  <%= provide :page_title, "New question" %>
  <% currently_at "New question" %>
  <h1 class="text-2xl">New question</h1>

  <%= render 'form', tags: @tags %>
</div>

app/views/questions/show.html.erb
<div class="content">
  <%= currently_at "Questions" %>
  <%= provide :page_title, "Show question" %>

  <%= render @question %>

  <%= render 'comments/commentable', commentable: @question, comment: @comment, html_id: 'questionComments' %>

  <div>
    <hr class="my-2 content">
    <h1 class="text-2xl font-bold">Write your answer</h1>
  </div>

  <div class="">
    <%= render "answers/form" %>
  </div>

  <%= turbo_frame_tag 'answers' do %>
    <div class="answers">
      <hr class="my-2">
      <h1 class="mb-4 font-bold text-2xl">Answers</h1>
        <div  class="my-2">
          <%= pagination @pagy %>
        </div>
        <%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question } %>
    </div>
  <% end %>
</div>

app/views/questions/update.turbo_stream.erb
<%= turbo_stream.replace @question, render(@question) %>