config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]


    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root to: 'pages#index'
  end
end

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages&.any?  %>
  <div class="alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="text-red-800"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |k, v| %>
  <%= tag.div v, class: "alert-#{k}", role: "alert" %>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="py-6 bg-gray-900 text-white">
    <nav class="container mx-auto flex items-center justify-between">

      <ul class="flex gap-4">
        <li><%= nav_tab t("menu.home"), root_url, class: "", current_page: current_page %></li>
        <li><%= nav_tab t("menu.questions"), questions_path, class: "", current_page: current_page %></li>
        <% if policy([:admin, :user]).index? %>
          <li><%= nav_tab "Dashboard", admin_users_path, class: "", current_page: current_page %></li>
        <% end %>
      </ul>

      <ul class="navbar_user flex gap-4 items-center">
          <% I18n.available_locales.each do |locale| %>
          <li>
            <%= link_to t(locale), url_for(params.to_unsafe_h.merge(locale: locale))  %>
          </li>
          <% end %>

        <% if user_signed_in? %>
          <li>
            <%= link_to edit_user_path(current_user), class: "flex items-center gap-2" do %>
              <%= current_user.gravatar %>
              <%= current_user.name_or_email %>
            <% end %>
          </li>

          <li>
            <%= link_to t("menu.logOut"), session_path, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </li>
        <% else %>
          <li><%= nav_tab t("menu.signIn"), new_user_path, class: "", current_page: current_page %></li>
          <li><%= nav_tab t("menu.logIn"), new_session_path, class: "", current_page: current_page %></li>
        <% end %>
      </ul>
    </nav>
  </header>
<% end %>