config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]


    resources :questions, concerns: :commentable do
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root to: 'pages#index'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Authorship
  include Commentable

  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include QuestionsAnswers
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create
  before_action :authorize_answer!
  after_action :verify_authorized

  def create
    @answer = @question.answers.build(answer_params.merge(user: current_user))
    if @answer.save
      set_respond_to question_path(@question),
                     'Answer created!',
                     query_decorate: true
    else
      load_questions_answers do_render: true
    end
  end

  def destroy
    @answer.destroy
    set_respond_to [ question_path(@question), status: :see_other ], 'Answer deleted!'
  end

  def edit; end

  def update
    if @answer.update answer_params
      set_respond_to question_path(@question, anchor: dom_id(@answer)),
                     'Answer updated',
                     query_decorate: true
    else
      render :edit
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find(params[:question_id])
  end

  def set_answer!
    @answer = @question.answers.find(params[:id])
  end

  def authorize_answer!
    authorize(@answer || Answer)
  end
end

app/views/answers/_answer.html.erb
<%= turbo_frame_tag answer do %>
  <%= tag.div class: "flex justify-between items-start mb-4 border-2 rounded p-4", id: dom_id(answer) do %>
    <div class="text-xl">
      <h2 class="font-bold text-xl flex gap-2 items-center">
        <%= question.user.gravatar %>
        <%= question.user.name_or_email %>
      </h2>
      <p class="mb-4"><%=  strip_tags(answer.body)  %></p>
      <p>
        <time datetime="<%= answer %>">
          <%= answer.formatted_created_at %>
        </time>
      </p>
    </div>
    <div>
      <% if policy(answer).edit? %>
        <%= link_to "Edit", edit_question_answer_path(question, answer), class: "btn-primary bg-gray-500" %>
      <% end %>
      <% if policy(answer).destroy? %>
        <%= link_to "Delete", question_answer_path(question, answer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-primary bg-red-500" %>
      <% end %>
    </div>
  <% end %>

  <%= render 'comments/commentable', commentable: @question, comment: @comment, html_id: dom_id(answer, 'comment_form') %>
<% end %>

app/views/answers/_form.html.erb
<%= turbo_frame_tag @answer do %>
  <%= form_with model: [@question, @answer], data: {turbo: false } do |form| %>
    <%=  render "shared/errors", object: @answer %>
    <div class="flex flex-col gap-4 w-full my-2">
      <div class="flex gap-2">
        <%= form.label :body, class: "w-4/12" %>
        <%= form.text_area :body, placeholder: "Body", class: "", required: true %>
      </div>
      <div class="mt-2">
        <%= form.submit "Submit", class: "btn-primary bg-blue-600" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.prepend 'answers', render(@answer, question: @answer.question)%>

app/views/answers/destroy.turbo_stream.erb
<%= turbo_stream.remove @answer %>

app/views/answers/edit.html.erb
<%= currently_at "Questions" %>
<%= provide :page_title, "Edit answer" %>
<%= render 'form' %>

app/views/answers/update.turbo_stream.erb
<%= turbo_stream.replace @answer, render(@answer, question: @answer.question) %>